---
answers:
  Dream on: 1
  Nice try: 1
  As if: 1
  Try Again: 1
  It is certain: 1
  It is decidedly so: 1
  Without a doubt: 1
  Yes, definitely: 1
  You may rely on it: 1
  As I see it, yes: 1
  Most likely: 1
  Outlook good: 1
  true: 1
  Signs point to yes: 1
  Reply hazy try again: 1
  Ask again later: 1
  Better not tell you now: 1
  Cannot predict now: 1
  Concentrate and ask again: 1
  Don't count on it: 1
  My reply is no: 1
  My sources say no: 1
  Outlook not so good: 1
  Very doubtful: 1
